--
-- CREATE KALYAN DATABASE
--
CREATE DATABASE IF NOT EXISTS kalyan;
--
-- CREATE TEST TABLE
--
CREATE EXTERNAL IF NOT EXISTS TABLE kalyan.test (line STRING) STORED AS TEXTFILE LOCATION '${INPUT}';
--
-- INSERT TEST TABLE DATA INTO OUTPUT DIRECTORY
--
INSERT OVERWRITE DIRECTORY '${OUTPUT}' SELECT * FROM kalyan.test;
