--
-- LOAD INPUT DATA INTO A BAG
--
A = LOAD '$INPUT' USING PigStorage(':');
--
-- COPY A BAG DATA INTO B BAG
--
B = FOREACH A GENERATE *;
--
-- STORE B BAG DATA INTO OUTPUT DIRECTORY
--
STORE B INTO '$OUTPUT' USING PigStorage(',');
